### ISSUE TITLE
screenshots of samples

### ISSUE THREAD

**Issue by ereaderDev** [JPTIZ/libgba-cpp#1]
Hello I have compiled the samples but I see some red lines, is this expected? 

It would be nice to have screenshots of samples so I can compare against my build.

**Comment by JPTIZ** [comment]
Hi.

Thanks for the suggestion, it would actually be a good thing. Since apparently there are people interested in this project, I might get more things done :)

About the red lines, actually I changed some things in the main code that accidentally broke some examples. I'm trying to get time to fix it. Can you tell which samples you tested?

By the way, I'm making some changes on API, preparing the engine part. This is being sketched in a separate `examples` branch (https://github.com/JPTIZ/libgba-cpp/tree/examples). The plan is to make a simple game's code in the way I would like de API to become, and then do the engine API with that implementation in mind. With that, I think that samples/tests will be more correct.

**Comment by Zaxuhe** [comment]
I'm having trouble compiling the examples, it seems like some files had changed names or structure

**Comment by JPTIZ** [comment]
Hi, @Zaxuhe.
Sorry about that, I think I should do more working/compilable commits. I've just got a little break on my undergrad course's tasks. Today starting this morning (now it's 0h30am here) I shall work a little more.

**Comment by Zaxuhe** [comment]
any updates?

**Comment by JPTIZ** [comment]
So, I finally got some time to update!

Here are the news:
- Examples have (most of them) been fixed;
- Screenshots added;
- Every example now has a readme file telling more about it, including what already works and what doesn't work yet. They're all linked in main readme.md.

I fixed them in `master` branch without the `examples` branch's changes for you to not have to wait for `examples` to be finished, since it may take a little longer than expected. All tests have been made with DevKitARM Release 47 (arm-none-eabi-g++ 7.1.0);
